encoding: utf-8
# Workaround for permalinks becoming global in jekyll 3
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
author:
  name: Abhay Rana
  url: https://about.me/n3m0
title: Abhay Rana
tagline: aka Nemo
description: |
  <div class="image">
    <img class="thumbnail" src="/img/profile.jpg">
  </div>
url: https://captnemo.in
baseurl: /
paginate: 3
paginate_path: "/page/:num/"
gems:
  - jekyll-paginate
  - jemoji
kramdown:
  input: GFM
  hard_wrap: false